name: UniUtils Documentation

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install DocFX
        run: choco install -y docfx

      - name: Use README.md as index.md
        run: cp README.md Documentation/index.md

      - name: Build documentation
        run: docfx Documentation/docfx.json

      - name: Upload site artifact
        uses: actions/upload-artifact@v4
        with:
          name: docfx-site
          path: Documentation/_site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download site artifact
        uses: actions/download-artifact@v4
        with:
          name: docfx-site
          path: _site

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: _site
